#!/usr/bin/env bash
set -e

help() {
  cat <<EOF
List datapoints (from the datapoint library)

Usage:
    c8y devmgmt datapoints list

    --name <string>           Match by name
    --label <string>          Match by c8y_Kpi.label
    --description <string>    Match by c8y_Kpi.description
    --fragment <string>       Match by c8y_Kpi.fragment
    --series <string>         Match by c8y_Kpi.series

Examples:
    c8y devmgmt datapoints list
    # List datapoints

    c8y devmgmt datapoints list --fragment Temperature --pageSize 100
    # List the first 100 datapoints with a specific fragment
EOF
}

OPTIONS=()
QUERY_PARTS=()

function join_by {
  local d=${1-} f=${2-}
  if shift 2; then
    printf %s "$f" "${@/#/$d}"
  fi
}

while [ $# -gt 0 ]; do
    case "$1" in
        --name)
            QUERY_PARTS+=(
              "name eq '$2'"
            )
            shift
            ;;

        --label)
            QUERY_PARTS+=(
              "c8y_Kpi.label eq '$2'"
            )
            shift
            ;;

        --description)
            QUERY_PARTS+=(
              "c8y_Kpi.description eq '$2'"
            )
            shift
            ;;

        --fragment)
            QUERY_PARTS+=(
              "c8y_Kpi.fragment eq '$2'"
            )
            shift
            ;;

        --series)
            QUERY_PARTS+=(
              "c8y_Kpi.series eq '$2'"
            )
            shift
            ;;

        -h|--help)
            help
            exit 0
            ;;

        *)
            REST_ARGS+=("$1")
            ;;

    esac
    shift
done

set -- "${REST_ARGS[@]}"

if [ "${#QUERY_PARTS[@]}" -gt 0 ]; then
  OPTIONS+=(
    --query
    "$(join_by " and " "${QUERY_PARTS[@]}")"
  )
fi

c8y inventory find --fragmentType c8y_Kpi "${OPTIONS[@]}" "$@"
