#!/usr/bin/env bash
set -e

help() {
  cat <<EOF
Execute a command on a device using an operation

Usage:
    c8y devmgmt execute <command> --device <device>

Examples:
    c8y devmgmt execute "ls -l" --device 12345
    # Execute a shell command on a device

    c8y devmgmt execute ./myscript.sh --device 12345
    # Execute a shell command which is stored as a shell script on a device

    c8y devices list | c8y devmgmt execute "ls -l"
    # Execute a shell command on multiple devices
EOF
}

if [ $# -lt 1 ]; then
    help
    exit 0
fi

COMMAND="$1"
shift

device_arg=()

REST_ARGS=()

while [ $# -gt 0 ]; do
    case "$1" in
        --device)
            device_arg+=("$1" "$2")
            shift
            ;;

        -h|--help)
            help
            exit 0
            ;;

        *)
            REST_ARGS+=("$1")
            ;;

    esac
    shift
done

set -- "${REST_ARGS[@]}"

if [[ -f "$COMMAND" ]]; then
    # Use is providing a file, so import the text from the file
    TEMPLATE="
{
    description: 'Execute command',
    c8y_Command: {
        text: importstr '$COMMAND',
    },
}
"
else
    # Command is provided as text
    TEMPLATE="
{
    description: 'Execute command',
    c8y_Command: {
        text: '$COMMAND',
    },
}
"
fi


c8y operations create "${device_arg[@]}" --template "$TEMPLATE" "$@"
