#!/usr/bin/env bash
set -e

help() {
  cat <<EOF
Restart a device by sending it an operation

Usage:
    c8y devmgmt devices restart --device <id|name>

Examples:
    c8y devmgmt devices restart --device 12345
    # Restart a single device

    c8y devices devices list | c8y devmgmt restart
    # Restart a list of devices
EOF
}

device_arg=()

REST_ARGS=()

while [ $# -gt 0 ]; do
    case "$1" in
        --device)
            device_arg+=("$1" "$2")
            shift
            ;;

        -h|--help)
            help
            exit 0
            ;;

        *)
            REST_ARGS+=("$1")
            ;;

    esac
    shift
done

set -- "${REST_ARGS[@]}"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
c8y operations create "${device_arg[@]}" --template "$SCRIPT_DIR/../templates/operations/restart.jsonnet" "$@"
